name: Test

on: [push]

env:
  CC: clang
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DCMAKE_C_COMPILER="${CC}" -DCUUTEST_EXAMPLE=on

      - run: cmake --build "${{github.workspace}}/build" --config "${{env.BUILD_TYPE}}"

      - run: ctest -C "${{env.BUILD_TYPE}}" --verbose
        working-directory: ${{github.workspace}}/build
